### ISSUE TITLE
SURVIVOR stats not working with Sniffles2 output

### ISSUE THREAD

**Issue by tuannguyen8390** [fritzsedlazeck/SURVIVOR#172]
Hi Fritz,

As title, I just try to use SURVIVOR (1.0.7) to check some stats with output from sniffles2 (2.0.6). But seems unable to do so. Any ideas ?

`SURVIVOR stats 20X_cohort.vcf 
`
```
vcf file
Min SV size (disable: -1)
Max SV size (disable: -1)
Min number read support (disable: -1)
output summary file
```

Many thanks,

Tuan

**Comment by Duda5** [comment]
Hi @tuannguyen8390, 
`SURVIVOR stats` is not working in your case because you have not provided a full list of arguments.

So, for example, the default command will look like this: 
`SURVIVOR stats 20X_cohort.vcf -1 -1 -1 SURVIVOR stats 20X_cohort.vcf.stats`.

To filter the output based on SV sizes and/or read support, replace `-1` options with your desired SV sizes in bp or read level, respectively.
Hope this helps!

**Comment by tuannguyen8390** [comment]
Works for me, many thanks !
