### ISSUE TITLE
options for merge 

### ISSUE THREAD

**Issue by shishuo16** [fritzsedlazeck/SURVIVOR#32]
Hi,

First, SURVIVOR is really a very good tool. I used it for merging structure variations of multi samples. But we also want to define the reciprocal overlap of SVs when we merge data. I wonder is there any chance you consider add this option for SURVIVOR ?

Best,
Shuo

**Comment by fritzsedlazeck** [comment]
Dear Shuo,
I do have a prototype for this, but it's not well tested.

I choose to implement the merge the way it is because of the following reasons:
1. Reciprocal overlap means that small variants get penalized in terms of not allowing their variance in position vs. large events. In theory that is actually against what one often observes. Eg. Small deletion or insertions are common in low complexity regions and thus need more flexibility for merging.
2. I am often interested in the lenght polymorphism especially for duplications. A reciprocal overlap often hinders the detection.
3. Most of the things the results will be the same or very similar. Depending on the threshold of the overlap. The merge as it is implemented works such that it compares the two start and the two end breakpoints of the SVs and allows only a certain deviation for each. Eg. 1kbp or whatever you set as a parameter.

Does that make sense?
Thanks
Fritz

**Comment by shishuo16** [comment]
Thank you for reply.
Yes, I understand the first point you said. But I have another question, is a certain breakpoint value Eg. 50bp  suitable for all SVs whose length ranging from 50bp to 30kbp? Should we increase the breakpoint parameter for large SVs?

**Comment by fritzsedlazeck** [comment]
You mean the distance parameter? Yes in our experiments most of the SV breakpoints that should get merged are lying within 50-60bp independent of the size. Note that the size of an event should not impact the precision of the breakpoint! 

However, we are currently often running the merge with 1kbp as the distance threshold. This is to account for repetitive elements where the breakpoints of the SV are more fuzzy. This has proven to be a good approximation.

**Comment by shishuo16** [comment]
OK. Thanks for reply. I am gonna try on my data.
