### ISSUE TITLE
VCF merge about strand

### ISSUE THREAD

**Issue by yuntwang** [fritzsedlazeck/SURVIVOR#50]
This will merge all the vcf files specified in sample_files together using a maximum allowed distance of 1kb, as measured pairwise between breakpoints (begin1 vs begin2, end1 vs end2). Furthermore we ask SURVIVOR only to report calls supported by 2 callers and they have to agree on the type (1) and on the **strand (1)** of the SV

Hi，@fritzsedlazeck,
I didn't understand the strand,can you explain it briefly?
Thanks

**Comment by fritzsedlazeck** [comment]
Sure. The different callers are reporting strand information sometimes. Eg. Delly with +/- and lumpy with 3to5 . We can use this to be very conservative when merging. However, it is also a hit risky if you are using other caller since we don't 100% know their notion. I personally don't use it.

I hope that helps.
Fritz

**Comment by yuntwang** [comment]
Thanks
