### ISSUE TITLE
Interpretation of sv-simulated bed file

### ISSUE THREAD

**Issue by svm-zhang** [fritzsedlazeck/SURVIVOR#6]
Hello Fritz,

I tried to use SURVIVOR to simulated a few number of SVs in one of the yeast reference genomes. The command line was:

SURVIVOR 1 yeast.fa par_file 0 simulated

Some lines of the bed output is as below:

NC_001139.9     **239105**  NC_001139.9     **246078**  DUP
NC_001137.3     **304464**  NC_001137.3     **305703**  DEL
NC_001134.8     **469961**  NC_001134.8     **474862**  INS
NC_001141.2     **186459**  NC_001141.2     **189325**  INV
NC_001137.3     **338964**  NC_001134.8     **210746**  TRA
NC_001137.3     **339552**  NC_001134.8     **211334**  TRA

I think I understand the insertion, deletion, and inversion lines. For instance, there is an insertion event from 469,961 to 474,852 on NC_001134.8 chromosome, right?

But I am not quite sure how to interpret the translocation and duplication lines.  Appreciate your help in advance!

Simo

**Comment by fritzsedlazeck** [comment]
Hi Simo,
yes the TRA were always hard. So the way SURVIVOR is simulating the TRA is to introduce balanced translocations. For example:

NC_001137.3 338964 NC_001134.8 210746 TRA
NC_001137.3 339552 NC_001134.8 211334 TRA

the region NC_001137.3 338964 - 339552 is swapped with NC_001134.8 210746 - 211334. So these events require 2 translocation events. Also note that these are always the same length to avoid further shifts. 

The duplication is that SURVIVOR takes the region NC_001139.9 239105- 246078 and pasts a copy of it next to it. -> tandem duplication. 

Does this help?
Cheers
Fritz

**Comment by svm-zhang** [comment]
Hello Fritz,

Thanks for the lighting response. Crystal clear.

I might ask you similar questions about INV-del, INV-dup, and INTRA-Trans later when I simulate them. Do you have plans to write a bit doc on each type of SVs on the wiki page? That would be very helpful.

Simo

**Comment by fritzsedlazeck** [comment]
Hi Simo,
yes definitely planed since like 1-2 months... :(  Lets keep that issue open until I wrote it up.
How to use it is written up here:
https://github.com/fritzsedlazeck/SURVIVOR/wiki#simulate-and-evaluate-svs

The nested stuff is simulated as each event after another. E.g. invdel: the two deletions and the one inversion are simulated such that they are adjacent, but reported independent of each other. 

I have to remove the INTRA that was just a try but never pushed it through. Its inactive in the code right now.  I also have updated code if you want to simulate ref but use real reads. 

Thanks for reaching out.
Fritz

**Comment by svm-zhang** [comment]
Hello Fritz,

The explanation on the nested SVs make sense. Thanks!

Does INTRA-Trans mean two translocation events within the same rather than different sequences?

cheers,
Simo

**Comment by fritzsedlazeck** [comment]
Kinda. I wanted to see what happens if I swap parts along the same chr. But I got lost along the way... Since I never really tested it I deactivated this part of the code. 

I really feel bad to not have the docu up to date, because SURVIVOR is actually a nice toolset and I use it on a daily bases across multiple projects. (sim + eval but more often the consensus (option 5)).

I will make another attempt to update the docu and make it easier to use. 
Cheers,
Fritz

**Comment by svm-zhang** [comment]
I ran sv simulation on refs and generate pacbio reads from the simulated ref, and do some calling and then evaluate calls. At least for me I like SURVIVOR toolset a lot. It would be even better with detailed docs.

Perhaps I have one more question about simulating pacbio reads. Is SURVIVOR able to simulate reads to a certain coverage, and/or a length dist, and/or an error rate profile?

cheers,
Simo

**Comment by fritzsedlazeck** [comment]
There are better Pacbio simulators. I was shooting for a straight forward one. The current version is not but I have a Nanopore like and Pacbio like simulator that are about to be finished. So there you can simply set the cov and read length and everything goes automatically. Unfortunately I am traveling the next 2 weeks and have to prepare stuff and finish up the Sniffles paper. So when I come back I can update this. 

Thanks
Fritz

**Comment by svm-zhang** [comment]
Nice! Can I say I am also looking forward to the Sniffles paper :) Please keep me posted.

**Comment by fritzsedlazeck** [comment]
Will do we are making the last edits and I hope we can upload it this or next week.

**Comment by fritzsedlazeck** [comment]
Dear Simo,
I extended the read simulation over the past days such that it now records an error profile of real data and generate reads based on this on the genome and coverage of your choice. I further started to write more documentation that you can find here:
https://github.com/fritzsedlazeck/SURVIVOR/wiki/Methods-and-Parameter
 
Feedback is more then welcome. 
Thanks
Fritz

**Comment by svm-zhang** [comment]
Hello Fritz,

Thanks for the update! I like this way of simulating reads, and I think it suits my analysis :) I will try it out and get back to you.

Simo

**Comment by fritzsedlazeck** [comment]
Great. There are error profiles now already in the folder that you can use if you like. 
Cheers
Fritz

**Comment by svm-zhang** [comment]
Thanks for letting me know. I will try them.

cheers,
Simo
