### ISSUE TITLE
how SURVIVOR merge works in case of DEL ?

### ISSUE THREAD

**Issue by unique379r** [fritzsedlazeck/SURVIVOR#71]
Hi Fritz,

Can you please clear my doubts that how DEL works in case of three different tools where None of these tools have same SVLEN in terms of Negative or Positive value .

SVMETHOD=SURVIVOR1.0.6

```
Breakdacner: SVLEN +ve value
Delly: There is  no SVLEN flag (Though i have some merge set which takes delly as well).
Lumpy: SVLEN -ve value

Example: 

###brekdancer
chr11	41104574	.	.	.	.	PASS	PROGRAM=breakdancer;SVTYPE=DEL;SVLEN=7426;END=41112000	GT:DP	1/.:0

###Delly
chr1	44215969	DEL00001487	AGTTGCTCATTAACATATGTTAAAAGTTTAAAAAGCAACCTTAATAAATATATGCTAAATAAACCAATTTCCTCACAATACACTTAGGATGTTAAAAAGAAGTTAAATT	A	.	PASS	PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=chr1;END=44216078;PE=0;MAPQ=60;CT=3to5;CIPOS=-1,1;CIEND=-1,1;INSLEN=0;HOMLEN=0;SR=4;SRQ=0.967391;CONSENSUS=TATATTTTCTATGCTAGCTAGAGACATGGCATTAGATACAATACAGTCCACCTCAGCTGTCCCAAAACTCAGGTTTGAATGTCACTATTCA;CE=1.95006	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	1/1:-20.2998,-1.50496,0:15:PASS:54:0:208:0:0:0:0:5

###Lumpy
chr1	44215969	2601	N	<DEL>	.	.	SVTYPE=DEL;STRANDS=+-:4;SVLEN=-111;END=44216080;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=4;PE=0;SR=4	GT:SU:PE:SR	./.:4:0:4

### Output from SURVIVOR (delly+lumpy) :
chr1	44215969	2601	N	<DEL>	.	PASS	SUPP=2;SUPP_VEC=011;SVLEN=-110;SVTYPE=DEL;SVMETHOD=SURVIVOR1.0.6;CHR2=chr1;END=44216080;CIPOS=0,0;CIEND=-2,0;STRANDS=+-	GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO	./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN	1/1:NA:109:0,5:+-:.:DEL:DEL00001487:AGTTGCTCATTAACATATGTTAAAAGTTTAAAAAGCAACCTTAATAAATATATGCTAAATAAACCAATTTCCTCACAATACACTTAGGATGTTAAAAAGAAGTTAAATT:A:chr1_44215969-chr1_44216078	./.:NA:111:0,4:+-:.:DEL:2601:NA:NA:chr1_44215969-chr1_44216080


```
Further i found SVLEN is different (few bases difference) than its reported in original tool.

Can you please explain ?
Thanks
Rupesh

**Comment by fritzsedlazeck** [comment]
Hey Rupesh,
so the negative and positive values are just norms from VCF. Recently it was defined that for deletions the sv len has to be negative. 

What SURVIVOR does it to try to parse the tag SVLen from the info field. Otherwise it tries to obtain it from the sequence that may be provided. The last resort is to take it from the start vs. end position. 

From how it is implemented now is that I am trying to make a good guess of what the most appropriate start and end coordinates are. E.g. here taken from Lumpy I assume. However, the SVLen is currently implemented as the average between all calls. It could make sense to just transfer it from the best guess call, but that is how it is at the moment. 

I hope that explains it. Let me know if you have further questions. 
Thansk
 Fritz
