### ISSUE TITLE
GL missing after merging

### ISSUE THREAD

**Issue by usevani** [fritzsedlazeck/SURVIVOR#94]
Hi Fritz, 

I noticed that GL values from single sample VCF FORMAT field do not make it into the merged VCF. Is there a reason to not include it in the merged VCF? If not, would it be possible to add that feature? 

thanks!

**Comment by fritzsedlazeck** [comment]
Can you show an example? This usually works. Please check also the version of SURVIVOR there was a bug in the parser..
Thanks
Fritz

**Comment by usevani** [comment]
Thanks for the quick reply. I am running the latest version 1.0.6 . Take a look at the example below.

Input
```
chr1    4228405 .       T       <INS:ME:ALU>    .       PASS    .  GT:GL   1/1:-393.2,-22.88,-1.21
chr1    4228405 .       T       <INS:ME:ALU>    .       PASS    .  GT:GL   1/1:-739.6,-43.35,-0.62
```

Output
`chr1    4228405 INS000SUR       T       <INS:ME:ALU>    .       PASS    SUPP=2;SUPP_VEC=11;SVLEN=280;SVTYPE=INS;SVMETHOD=SURVIVOR1.0.6;CHR2=chr1;END=4228685;CIPOS=0,0;CIEND=0,0;STRANDS=+-     GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO     1/1:NA:280:0,0:+-:.:INS:.:NA:NA:chr1_4228405-chr1_4228685       1/1:NA:280:0,0:+-:.:INS::NA:NA:chr1_4228405-chr1_4228685`

Command
`lib/SURVIVOR-1.0.6/Debug/SURVIVOR merge inputs 50 1 1 0 0 0 out.1.0.6.vcf`

**Comment by fritzsedlazeck** [comment]
Oh sorry, I thought you mean the GT. 
Yes SURVIVOR does not carry over the GL because the parser does not parse it.
One of the major challenges with these VCF files is that they are so variable especially in the amount of information they provide. SURVIVOR is designed just to take the minimum information and thus does not parse GL because its not always provided.
Sorry about the confusion.
Cheers
Fritz
